# Generated by Django 6.0.7 on 2026-07-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="competed",
            field=models.BooleanField(default=False),
        ),
    ]
